<!DOCTYPE html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Reporte Usuarios</title>
</head>
<body>
    <table>
    	<thead>
            <tr>
                <td>Codigo Usuario</td>
                <td>Usuario</td>
                <td>Email</td>
                <td>Dni</td>
                <td>Nombre</td>
                <td>Apellido Paterno</td>
                <td>Apellido Materno</td>
                <td>Condicion</td>
                <td>Accciones</td>
            </tr>
    	</thead>    	
    	<tbody>
          <?php
//             foreach($this->fil as $tm){  
//                echo '<tr>
//                        <td>'.$tm['iUsuIdUsuario'].'</td>
//                        <td>'.$tm['vUsuUsuario'].'</td>                            
//                        <td>'.$tm['vUsuEmail'].'</td>                                
//                        <td>'.$tm['cUsuDni'].'</td> 
//                        <td>'.$tm['vUsuNombre'].'</td> 
//                        <td>'.$tm['vUsuApellidoPat'].'</td> 
//                        <td>'.$tm['vUsuApellidoMat'].'</td> 
//                        <td>'.$tm['cUsuEstado'].'</td> 
//                        <td><a><img alt="Eliminar" /></a> <a><img alt="Editar" /></a> </td>                             
//                      </tr>';            
//
//             }          
          ?>
        </tbody>
    </table>
</body>

