<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <object align="" width="100%" height="100%" id="lasuma" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
            <param value="./juegos/espacioMultiplica.swf" name="movie"> 
            <param value="high" name="quality"> 
            <param value="#CC9933" name="bgcolor"> 
            <embed align="" width="100%" height="550" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" name="senior pi" bgcolor="#CC9933" quality="high" src="espacioMultiplica.swf">
        </object>        
    </body>
</html>
