<?php
//$html= new Application_Model_Html();
//$seccion=$this->array_re;
//$contenido='<select id="cboseccion" name="cboseccion">';
//$temp='<script>elem=$("#cboseccion");';
//foreach($seccion as $aux){
////    $contenido.='<option value="'.$aux['iSeccIdSeccion'].'">'.$aux['vSeccDescripcion'].'</option>';
//    $temp.='elem.appendChild(<option value="'.$aux['iSeccIdSeccion'].'">'.$aux['vSeccDescripcion'].'</option>)';
//}
//$temp.='</script>';
// $contenido.='</select>';
//print $html->crearContentAjax($temp);
?>
<!--<script type="text/javascript" src="/js/jquery/jquery-1.4.2.min.js"></script>-->
