<?php
    $this->titulopagina='Los Pinos - "Cursos"';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $curso=new Application_Model_Cursos();

    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';

    $script='<script type="text/javascript" src="/js/jquery-ui/jquery-ui-1.8.16.custom.min.js" > </script>
	<script type="text/javascript">
	$(function() {
		var stop = false;
		$( "#accordion h3" ).click(function( event ) {
			if ( stop ) {
				event.stopImmediatePropagation();
				event.preventDefault();
				stop = false;
			}
		});
		$( "#accordion" )
			.accordion({
				header: "> div > h3",
                                active: false,
                                collapsible: true
			})
			.sortable({
				axis: "y",
				handle: "h3",
				stop: function() {
					stop = true;
				}
			});
	});
	</script>      
        ';
    $this->script=$script;
    
    $css='<link media="projection, screen" href="/js/jquery-ui/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css">';
    $this->css=$css;
    
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='<ul class="bread">
             <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <a href="cursos" class="breadcrumb breadcrumb0" target="_top">
                    <span>Cursos</span>
                </a>
            </li>
        </ul>';
    $contenido = '
        <div class="admin_section treinta" >
            <h4><img src="/main/img/course.gif" alt="Cursos" title="Cursos"> Cursos</h4>
            <ul>
                <li><a href="nuevocurso">Crear un curso</a></li>                
                <li><a href="course_list.php">Lista de cursos</a></li>
                <li><a href="course_export.php">Exportar cursos</a></li>
                <li><a href="course_import.php">Importar cursos desde un fichero</a></li>
                <li><a href="course_category.php">Categorías de cursos</a></li>
                <li><a href="subscribe_user2course.php">Inscribir usuarios en un curso</a></li>
            </ul>
        </div>
        <div class="admin_section setenta">
           
<div id="accordion">';
$contenido.=$curso->CrearAcordiongrados();
$contenido.='</div>';
    
    print $html->crearWrapper(null, null, null, $h3, $h4 ,null, null,$contenido);
?>

