<?php
    
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();   
    $tipousuario= new Application_Model_TipoUsuario();
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    $script='<script type="text/javascript" src="/js/jquery.form.js" ></script>
        <script type="text/javascript"> 
            // wait for the DOM to be loaded 
           $(document).ready(function() { 
            // bind "formLogin" and provide a simple callback function 
            $("#formLogin").ajaxForm(function() { 
                alert("Gracias por sus buenos Deseos!"); 
            }); 
        });         
        </script>';
    $this->script=$script;
    $this->titulopagina='Aula Virtual "LOS PINOS"';
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='<ul class="bread">
            <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <span>Mi Página principal</span>
            </li>
        </ul>';
    
    $contenido =$this->formagregarusuario;
    
    print $html->crearWrapper(null, null, null, $h3, $h4, $this->layout()->content,null,$contenido);


    ?>