<script type="text/javascript">   
     function cargarseccion(){
        var valor=$("#cbogrado").val();
            elem=document.getElementById('cboseccion');
            $("#cboseccion").html('<option>Cargando...</option>');
            var option;
            $.getJSON("listarsecciongrado/?codgrad="+valor, function(data){
                var seccion = data;var option;
                for (var x = 0 ; x < seccion.length ; x++) {
                    option+='<option value='+seccion[x].iSeccIdSeccion+'>'+seccion[x].vSeccDescripcion+'</option>';
                }
                 $("#cboseccion").html(option);
           });
        }   
        
        
function dibujar(){
$(function () {
    $.getJSON("reporteusualumno/", function(data){
        var dataset1 = data;var d1=new Array();
        for(var x = 0 ; x < dataset1.length ; x++){
            d1[x]=[dataset1[x].iAlumIdAlumno,dataset1[x].iUsuIdUsuario];
        }
        data=[{"label":"VINCES","data":d1}];
        console.log(d1);
        console.log(data);
    $.plot($("#placeholder"), data);        
   });

});
}



$.elycharts.templates['line_basic_5'] = {
 type : "line",
 margins : [10, 10, 20, 50],
 style : {
  background : "url(sites/elycharts.com/files/sky.jpg)"
 },
 defaultSeries : {
  plotProps : {
   opacity : 0.6
  },
  highlight : {
   overlayProps : {
    fill : "white",
    opacity : 0.5
   }
  },
  startAnimation : {
   active : true,
   type : "grow"
  },
  tooltip : {
   frameProps : false,
   height : 20,
   offset : [10, 0],
   contentStyle : "font-weight: bold"
  }
 },
 series : {
  serie1 : {
   color : "red"
  },
  serie2 : {
   color : "blue"
  }
 },
 defaultAxis : {
  labels : true
 },
 features : {
  grid : {
   draw : [true, false],
   forceBorder : false,
   evenHProps : {
    fill : "yellow",
    opacity : 0.2
   },
   oddHProps : {
    fill : "green",
    opacity : 0.2
   }
  }
 }
}
$(document).ready(function(){

$("#placeholder").chart({
 template : "line_basic_5",
 tooltips : {
  serie1 : ["a", "b", "c", "d"],
  serie2 : ["a", "b", "c", "d"]
 },
 values : {
  serie1 : [39, 42, 98, 74],
  serie2 : [15, 30, 2, 63]
 },
 defaultSeries : {
  type : "bar"
 },
 barMargins : 10
});
});

</script>
    
    
}        
</script>

<?php
    $this->titulopagina='Los Pinos - Nuevo Curso';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $script='
        <script type="text/javascript" src="/js/codigito.js" > </script>
        <script type="text/javascript" src="/js/jquery-ui/jquery-ui-1.8.16.custom.min.js" > </script>
        <script type="text/javascript" src="/js/graficas/jquery.flot.js"></script>
        <script type="text/javascript" src="/js/graficas/excanvas.min.js"></script>
        <script type="text/javascript" src="/js/graficas/elycharts.js"></script>
        <script type="text/javascript" src="/js/graficas/raphael.js"></script>        
        <script type="text/javascript" src="/js/graficas/chart.js"></script>           
        <script type="text/javascript" src="/js/graficas/jqBarGraph.1.1.js"></script>        
        ';
    $this->script=$script;
    $css='<link media="projection, screen" href="/js/jquery-ui/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css">';
    $this->css=$css;
    
    $h3 = '<ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
           
        $contenido = '
            <div class="admin_section treinta"> 
                <h4>Registrar Nuevo Curso</h4>'.$this->formularioagregarcurso.'
                <button onclick="dibujar();">Dibujame</button>
                <button onclick="dibu();">Dibujame</button>
                <button onclick="dibujaporsexo();">Dibuja JQBART</button>
            </div>
            <div class="admin_section setenta">
                <h4>Graficos</h4>
                <div id="exampleSimple" style="width: 400px; height: 300px; position: relative; text-align: center;">

                </div>
                <div id="placeholder" style="width: 400px; height: 300px; position: relative; text-align: center;">

                </div>

               ';

        $contenido .= '
            </div>';
    $mensaje='
    <div id="dialog-confirm" title="Advertencia" style="display:none">
        <p>
            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Esta Seguro de Confirmar?
        </p>
    </div>';
    print $html->crearContentAjax($mensaje);
    print $html->crearWrapper(null, null, null, $h3, null ,$this->layout()->content, null,$contenido);
?>