<script type="text/javascript">   
    
function dibujar(){
$(function () {
    $.getJSON("reporteusualumno/", function(data){
        var dataset1 = data;var d1=new Array();
        for(var x = 0 ; x < dataset1.length ; x++){
            d1[x]=[dataset1[x].iAlumIdAlumno,dataset1[x].iUsuIdUsuario];
        }
        data=[{"label":"VINCES","data":d1}];
        console.log(d1);
        console.log(data);
    $.plot($("#placeholder"), data);        
   });

});
}        
</script>

<?php
    $this->titulopagina='Los Pinos - Nuevo Curso';
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();    
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    
    $script='
        <script type="text/javascript" src="/js/jquery-ui/jquery-ui-1.8.16.custom.min.js" > </script>
        <script type="text/javascript" src="/js/graficas/raphael.js"></script>        
        <script type="text/javascript" src="/js/graficas/elycharts.js"></script>
        <script type="text/javascript" src="/js/graficas/prueba.js"></script>           
        ';
    $this->script=$script;
    $css='<link media="projection, screen" href="/js/jquery-ui/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css">
<style>
.charlab { font-face: helvetica, arial; color: black; margin: 0; }
.date { font-size: 10px; font-weight: normal }
.visits { color: #5Af; font-weight: normal }
.hits { color: #F80; font-weight: normal }
.label { font-size: 12px; line-height: 14px; margin-left: 2px; font-weight: bold }    
    
</style>
';
    $this->css=$css;
    
    $h3 = '<ul id="logout">
            <li>
                <a href="/admin/logout/" target="_top">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
           
        $contenido = '
            <div class="admin_section treinta"> 
                <h4>Registrar Nuevo Curso</h4>'.$this->formularioagregarcurso.'
                <button onclick="dibujar();">Dibujame</button>
                <button onclick="dibu();">Dibujame</button>
                <button onclick="pinta();">Dibuja JQBART</button>
            </div>
            <div class="admin_section setenta">
                <h4>Graficos</h4>
<div id="chart" style="width: 100%; height: 200px">
</div>
               ';

        $contenido .= '
            </div>';
    $mensaje='
    <div id="dialog-confirm" title="Advertencia" style="display:none">
        <p>
            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Esta Seguro de Confirmar?
        </p>
    </div>';
    print $html->crearContentAjax($mensaje);
    print $html->crearWrapper(null, null, null, $h3, null ,$this->layout()->content, null,$contenido);
?>