<?php
    
    $html= new Application_Model_Html();
    $menu= new Application_Model_Menu();
    $usuario= new Application_Model_Usuario();   
    $tipousuario= new Application_Model_TipoUsuario();
    
    $mysession = new Zend_Session_Namespace('sesion');                    
    $paginaActual=$mysession->paginaActual ;
    $nombreUsuario=$mysession->usuario_nombre;
    $usuario_id=$mysession->usuario_id;
    $script='<script type="text/javascript" src="/js/jquery.form.js" ></script>

        <script type="text/javascript">
            var ln = "es";
                if(self.location != top.location) top.location = "/" + ln;
        </script>

	<!--<script type="text/javascript" src="http://math.cilenia.com/js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="http://math.cilenia.com/js/jquery.form.js"></script>
	<script type="text/javascript" src="http://math.cilenia.com/js/lib.min.js"></script>
	<script type="text/javascript" src="http://math.cilenia.com/js/Math/Languages/es.js"></script>
	<script type="text/javascript" src="http://math.cilenia.com/js/main.min.js"></script>-->

 
        

       
';
    
    $css='<link href="/css/tablero.css" rel="stylesheet" type="text/css">';

    $this->script=$script;
    $this->titulopagina='Aula Virtual "LOS PINOS"';
    $this->css=$css;
    $h3 = '
        <ul id="logout">
            <li>
                <a href="/admin/logout/">
                    <span>Cerrar Sesión de '.$nombreUsuario.'</span>
                </a>
            </li>
        </ul>';
 
    $tipo=$mysession->tipo_usuario;
    $result = $menu->getMenu($tipo);
    
    $h3 .= '<ul>'; 
    foreach ($result as $aux) {
       if ($paginaActual==$aux['Descripcion']){
           $h3.='<li id="current">';
       }
       else {
           $h3.='<li>';
       }
       
       $h3.='
           <a href="'.$aux['url'].'" target="_top">
                    <span id="tab_active">'.$aux['Descripcion'].'</span>
                </a>
            </li>';
    }
    $h3 .= '</ul>';
    
    $h4='<ul class="bread">
            <li>
                <a class="home" href="/">
                    <img align="middle" src="/main/css/home.png" alt="Página principal" title="Página principal">
                </a>
            </li>
            <li>
                <span>Mi Página principal</span>
            </li>
        </ul>';
    
    $contenido ='
        
<div class="clearfix" id="menuContainer">
			<div class="inner">
				<ul id="menu">
					<li class="active"><a rel="+" class="addition" href="javascript:;"><strong>Sumas</strong></a></li>
					<li class=""><a rel="-" class="subtraction" href="javascript:;"><strong>Restas</strong></a></li>
					<li class=""><a rel="*" class="multiplication" href="javascript:;"><strong>Multiplicaciones</strong></a></li>
					<li class=""><a rel="/" class="division" href="javascript:;"><strong>Divisiones</strong></a></li>
				</ul>
				<ul class="annonce">
					<li><a id="comparison" href="/comparison/es"><strong>&lt; = &gt;</strong></a></li>
					<li><a id="clock" href="/clock/es"><strong>Reloj y el tiempo</strong></a></li>
				</ul>
			</div>
		</div>

            <div id="playground">
					<div class="status">
						<div class="gameBoard">
							<dl>
								<dt class="timeDisplay label" style="display: none;">Tiempo:</dt>
								<dd class="timeDisplay time" style="display: none;">00:30</dd>
								<dt>Preguntas respondidas:</dt>
								<dd class="answers" style="display: block;">21</dd>
								<dt>Respuestas equivocadas:</dt>
								<dd class="errors" style="display: block;">14</dd>
							</dl>
						</div>
						<strong class="total" style="display: inline;">95</strong>&nbsp;puntos					</div>
					<div id="equation">
						<span id="operand_0_Holder"><input type="text" title="Informa tu número y aprieta Enter" class="operand" id="operand_0" name="operand_0" readonly=""></span>
						<span class="operatorHolder" id="operator">+</span>
						<span id="operand_1_Holder"><input type="text" title="Informa tu número y aprieta "\"Enter"\"" class="operand" id="operand_1" name="operand_1" readonly=""></span>
						<span class="operatorHolder">=</span>
						<span id="operand_2_Holder"><input type="text" title="Informa tu número y aprieta Enter" class="operand answer active" id="operand_2" name="operand_2"></span>
					</div>
					<p id="messageWrapper"><span></span></p>
				</div>';
$contenido.='
    <div id="navigation">
			<div class="inner">
<!--				<h2 class="headline">Practice Your Math</h2>-->
				<div class="clearfix box settings">
					<fieldset class="clearfix leftCol">
						<h3 class="title">Dificultad</h3>
		    			<ul class="clearfix rangeSelector range1">
							<li>
								<label title="números 1 a 5" for="range1_2">
									<input type="radio" value="1|5" id="range1_2" name="range1">
									Muy fácil								</label>
							</li>
							<li>
								<label title="números 1 a 10" for="range1_3">
									<input type="radio" value="1|10" id="range1_3" name="range1">
									Fácil								</label>
							</li>
							<li>
								<label title="números 1 a 20" for="range1_4">
									<input type="radio" value="1|20" id="range1_4" name="range1">
									Algo fácil								</label>
							</li>
							<li>
								<label title="números 1 a 100" for="range1_5">
									<input type="radio" value="1|100" id="range1_5" name="range1">
									No tan fácil								</label>
							</li>
						</ul>

						<div class="clearfix rangeSelector range2" style="display: none;">
							<p>Elige los números</p>
							<p class="clearfix"><!--<label for="range2_start">Rango</label>-->
								<select id="range2_start" name="range2_start">
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<option value="5">5</option>
									<option value="6">6</option>
									<option value="7">7</option>
									<option value="8">8</option>
									<option value="9">9</option>
								</select>
								, <select id="range2_end" name="range2_end">
									<option value="">---</option>
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<option value="5">5</option>
									<option value="6">6</option>
									<option value="7">7</option>
									<option value="8">8</option>
									<option value="9">9</option>
								</select>
							</p>
						</div>
					</fieldset>


					<fieldset class="clearfix rightCol">
						<h3 class="title">Posición de la incógnita</h3>

						<ul class="clearfix positionSelector">
							<li class="xPosition1">
								<label for="xPosition1">
									<input type="radio" value="3" id="xPosition1" name="xPosition">
									<span>1 + 2 = <strong>__</strong></span>
								</label>
							</li>
							<li class="xPosition2">
								<label for="xPosition2">
									<input type="radio" value="2" id="xPosition2" name="xPosition">
									<span>1 + <strong>__</strong> = 3</span>
								</label>
							</li>
							<li class="xPosition3">
								<label for="xPosition3">
									<input type="radio" value="1" id="xPosition3" name="xPosition">
									<span><strong>__</strong> + 2 = 3</span>
								</label>
							</li>
						</ul>
					</fieldset>
				</div>



				<p class="actions clearfix call practice">Práctica:
					<a class="practice secondaryAction" href="javascript:;">Continuar</a>
					<a class="newGame secondaryAction1" href="javascript:;">Empieza aquí</a>
				</p>

				<div class="clearfix box call">
					<h3 class="title">¿Listo para empezar a probar tus habilidades matemáticas?</h3>
					<p class="tease clearfix">
						Elige el tiempo<br>
						<select id="xTime" name="xTime">
							<option value="30">30 segundos</option>
							<option value="45">45 segundos</option>
							<option value="60">1 minuto</option>
							<option value="75">1 minuto 15 segundos</option>
							<option value="90">1 minuto 30 segundos</option>
							<option value="120">2 minutos</option>
							<option value="180">3 minutos</option>
							<option value="240">4 minutos</option>
							<option value="300">5 minutos</option>
						</select>
					</p>
					<p class="actions clearfix">
						<a class="StartXTimeGame primaryAction" href="javascript:;">Empezar un juego nuevo</a>
					</p>
				</div>

				<p class="links clearfix">
					<a rel="#resultBox" class="viewResult overlayTrigger" href="javascript:;">Puntuación</a>
					<a rel="#helpBox" class="viewHelp overlayTrigger" href="javascript:;">Ayuda</a>
				</p>

			</div>
		</div>
<div id="resultBox" class="modal" style="position: absolute; z-index: 9999; top: 590.6px; left: 422.5px; display: block;">
			<h2>Puntuación</h2>
			<h4 class="gameoverTime">mar 22 nov 2011 10:54:39 PET</h4>

			<dl>
				<dt>Operación:</dt>
				<dd class="operation">Sumas</dd>
				<dt>Rango:</dt>
				<dd>Números desde <span class="min">1</span> a <span class="max">5</span></dd>
				<dt>Tiempo:</dt>
				<dd class="gameTime">00:30</dd>
				<dt>puntos:</dt>
				<dd class="points">0</dd>
				<dt>Preguntas respondidas:</dt>
				<dd class="answers" style="display: block;">0</dd>
				<dt>Respuestas equivocadas:</dt>
				<dd class="errors" style="display: block;">0</dd>
			</dl>


			<!-- yes/no buttons -->
			<p class="actions"><a class="close secondaryAction1" href="javascript:;"> Cerrar </a></p>
		</div>                
    ';
    
    print $html->crearWrapper(null, null, null, $h3, $h4, $this->layout()->content,null,$contenido);


?>